### ISSUE TITLE
Docker laravel-k8s-demo image

### ISSUE THREAD

**Issue by jasperf** [BillWilson/laravel-k8s-demo#1]
Hi there Bill, thanks for sharing this! Been working on a version of this at https://github.com/smart48/l8 so I can work locally with Docker, set up K8 with Terraform and use K8 for deployment. 

I saw you use `asia.gcr.io/billshiun/laravel-k8s-demo` at `deploy/app/deploy.yml` . Is this an image with the entire laravel app inside of it? Like https://hub.docker.com/r/bitnami/laravel perhaps? 

Would it be possible to share how the actual `Dockerfile` looks like?

**Comment by jasperf** [comment]
I see now that it must be based on the app / php-fpm `Dockerfile` https://github.com/smart48/l8/blob/master/deploy/Dockerfile .. but what about the Nginx service?

**Comment by BillWilson** [comment]
> I see now that it must be based on the app / php-fpm `Dockerfile` https://github.com/smart48/l8/blob/master/deploy/Dockerfile .. but what about the Nginx service?

@jasperf 
Yeah, You got it. I have a different dockerfile for k8s to deploy on GCP in the deploy folder.

I build the image before I deploy the container. You can follow my steps in [README](https://github.com/BillWilson/laravel-k8s-demo/blob/master/README.md).

The Nginx service is at the end of [dockerfile](https://github.com/BillWilson/laravel-k8s-demo/blob/cb3afb30de16c97620aa260328a9bafc74fe873d/deploy/Dockerfile#L39)

I checked some articles for the way how they use PHP-fpm and Nginx in a pod rather than in a container. The best one I got is copying the entire application folder from the PHP-fpm's container to the Nginx's container before [(Ref)](https://matthewpalmer.net/kubernetes-app-developer/articles/php-fpm-nginx-kubernetes.html).

This way may cause some problems when your application folder is huge( > 1GB) and will make the deployment slower than you can tolerate.

**Comment by BillWilson** [comment]
BTW, this example is just the demo for my tech talk. You have to modify the setting and try to build the container with the cloud build or some similar pipeline service before deploy to the production environment.

**Comment by jasperf** [comment]
> I checked some articles for the way how they use PHP-fpm and Nginx in a pod rather than in a container. The best one I got is copying the entire application folder from the PHP-fpm's container to the Nginx's container before (Ref).
> This way may cause some problems when your application folder is huge( > 1GB) and will make the deployment slower than you can tolerate.

Thanks for this information. Very useful. They way Matthew added a PHP and Nginx container in one deployment file inside one pod is a cool approach and I may buy his e-book. Did not see you or others use this kind of setup before using:

```
# Create a pod containing the PHP-FPM application (my-php-app)
# and nginx, each mounting the `shared-files` volume to their
# respective /var/www/html directories.

kind: Pod
apiVersion: v1
metadata:
  name: phpfpm-nginx-example
spec:
  volumes:
    # Create the shared files volume to be used in both pods
    - name: shared-files
      emptyDir: {}
    
    # Add the ConfigMap we declared above as a volume for the pod
    - name: nginx-config-volume
      configMap:
        name: nginx-config

  containers:
    # Our PHP-FPM application
    - image: my-php-app:1.0.0
      name: app
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
      # Important! After this container has started, the PHP files
      # in our Docker image aren't in the shared volume. We need to 
      # get them into the shared volume. If we tried to write directly
      # to this volume from our Docker image the files wouldn't appear
      # in the nginx container.
      #
      # So, after the container has started, copy the PHP files from this
      # container's local filesystem (/app -- added via the Docker image) 
      # to the shared volume, which is mounted at /var/www/html.
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "cp -r /app/. /var/www/html"]
    
    # Our nginx container, which uses the configuration declared above,
    # along with the files shared with the PHP-FPM app.
    - image: nginx:1.7.9
      name: nginx
      volumeMounts:
        - name: shared-files
          mountPath: /var/www/html
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
```

We will probably have an app with more than 1GB. And we will want to separate shared data - client files, secret keys and `.env` - from the core application data. So we will be probably be separating code from the image. 

We will continue using [PHP Deployer](https://github.com/deployphp/deployer) or another orchestration tool to push code updates to the server. If you do have recommendations there please let me know. PHP Deployer is cool, but to deploy I need fancy commands like 
```
host('SERVER-IP')
    ->set('deploy_path', '/path/to/deployer')
    ->set('bin/php', 'cd /path/to/laradock/ && docker-compose exec -T workspace php')
    ->set('bin/composer', 'cd /path/to/laradock/ && docker-compose exec -T workspace composer -d={{release_path}}');
```
and to reload this:
```
set('php_fpm_service', 'php7.3-fpm');
set('php_fpm_command', 'echo "" | sudo -S /usr/sbin/service {{php_fpm_service}} reload'); // for setups like laravel forge
set('php_fpm_command', "kill -USR2 "$(ps -ef | grep '[p]hp-fpm: master' | awk '{print $2}')""); // for docker based setups with laradock or similar

task('fpm:reload', function () {
run('{{php_fpm_command}}');
})->desc('Reload the php-fpm service');
```
What I also missed is a queues container like Beanstalkd, Laravel Horizon, a workspace container to manage all and a PHP worker. These we will probably add based on how Laradock does it.
